#!/usr/bin/env python3
"""
Obsidian Knowledge Vault Exporter (2026 SOTA Framework - v1.0)
- Neon DB 및 지식 그래프에 등록된 모든 기술, 인물, 연구소, 논문을 Obsidian [[wikilinks]] 형태의 마크다운 볼트로 원클릭 변환
- 실제 Obsidian 앱에서 열어 그래프 뷰를 완벽하게 탐색 가능
"""

import json
import os
import re
import sys

# Ensure UTF-8
if sys.stdout.encoding != 'utf-8':
    try:
        sys.stdout.reconfigure(encoding='utf-8')
    except Exception:
        pass

base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
vault_dir = os.path.join(base_dir, "obsidian_vault")

def export_vault():
    graph_path = os.path.join(base_dir, "configs", "tech_graph_schema.json")
    if not os.path.exists(graph_path):
        print("[-] Schema not found.")
        return

    with open(graph_path, "r", encoding="utf-8") as f:
        schema = json.load(f)

    nodes = schema.get("graph", {}).get("nodes", [])
    links = schema.get("graph", {}).get("links", [])

    # Subdirectories in Vault
    tech_dir = os.path.join(vault_dir, "Technologies")
    person_dir = os.path.join(vault_dir, "People")
    org_dir = os.path.join(vault_dir, "Organizations")
    paper_dir = os.path.join(vault_dir, "Papers")

    for d in [vault_dir, tech_dir, person_dir, org_dir, paper_dir]:
        os.makedirs(d, exist_ok=True)

    # Build node link map
    out_links_map = {}
    in_links_map = {}

    for l in links:
        s = l["source"] if isinstance(l["source"], str) else l["source"]["id"]
        t = l["target"] if isinstance(l["target"], str) else l["target"]["id"]
        rel = l.get("relation", "RELATES_TO")
        
        if s not in out_links_map: out_links_map[s] = []
        out_links_map[s].append((t, rel))

        if t not in in_links_map: in_links_map[t] = []
        in_links_map[t].append((s, rel))

    node_dict = {n["id"]: n for n in nodes}

    print(f"\n[*] Exporting {len(nodes)} entities to Obsidian Vault at: {vault_dir}")

    exported_count = 0
    for n in nodes:
        nid = n["id"]
        label = n.get("label", nid)
        clean_label = re.sub(r'^[^\w\s]+', '', label).strip().split('(')[0].strip()
        ntype = n.get("type", "tech")
        group = n.get("group", "general")
        gen = n.get("gen", "Gen X")
        desc = n.get("desc", "")
        mentions = n.get("mentions", 0)

        # Target Dir
        if ntype == "person":
            target_folder = person_dir
        elif ntype == "org":
            target_folder = org_dir
        elif ntype == "paper":
            target_folder = paper_dir
        else:
            target_folder = tech_dir

        safe_filename = "".join(c for c in clean_label if c.isalnum() or c in (' ', '_', '-')).rstrip() + ".md"
        filepath = os.path.join(target_folder, safe_filename)

        content = f"""---
id: "{nid}"
type: "{ntype}"
domain: "{group}"
generation: "{gen}"
mention_score: {mentions}
tags:
  - tech-lineage
  - {group}
  - {ntype}
---

# {label}

> **엔티티 분류**: `{ntype.upper()}` | **도메인**: `{group}` | **세대**: `{gen}`

## 📖 핵심 설명
{desc}

## 🔗 연관된 선조 및 인용 관계 (Outgoing Links)
"""
        outgoing = out_links_map.get(nid, [])
        if outgoing:
            for (target_id, rel) in outgoing:
                target_node = node_dict.get(target_id, {})
                t_label = target_node.get("label", target_id).split('(')[0].strip()
                content += f"- **{rel}** ➔ [[{t_label}]]\n"
        else:
            content += "- *연결된 후속 링크 없음*\n"

        content += "\n## 📥 이 기술을 인용/상속한 엔티티 (Incoming Backlinks)\n"
        incoming = in_links_map.get(nid, [])
        if incoming:
            for (source_id, rel) in incoming:
                source_node = node_dict.get(source_id, {})
                s_label = source_node.get("label", source_id).split('(')[0].strip()
                content += f"- [[{s_label}]] ➔ *({rel})*\n"
        else:
            content += "- *참조하는 역방향 백링크 없음*\n"

        content += "\n---\n*Auto-generated by AI Tech-Lineage Network Agent*\n"

        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)
        exported_count += 1

    # Create Root Index.md
    index_path = os.path.join(vault_dir, "00_Tech_Lineage_Index.md")
    with open(index_path, "w", encoding="utf-8") as f:
        f.write(f"""# 🕸️ AI Tech Lineage & Citation Knowledge Vault

총 **{len(nodes)}개**의 핵심 기술, 연구자, 연구기관, 1차 논문이 `[[Wikilinks]]` 양방향 인용망으로 연결되어 있습니다.

## 📁 주요 폴더 구조
- `Technologies/`: 0세대 원시 엔진부터 3세대 SOTA까지의 소프트웨어/모델
- `People/`: 패러다임을 창시한 핵심 연구자 및 아키텍트
- `Organizations/`: 글로벌 최고 권위 AI 연구소 및 기업
- `Papers/`: 1차 연구 논문 및 벤치마크 테크니컬 리포트

## 🚀 빠른 링크
- [[CUDA]] ➔ [[FlashAttention]] ➔ [[vLLM]] ➔ [[SGLang]]
- [[BeautifulSoup]] ➔ [[Scrapy]] ➔ [[Firecrawl]] ➔ [[WaterCrawl]]
- [[Lianmin Zheng]] (UC Berkeley LMSYS) ➔ [[SGLang]]
- [[Woosuk Kwon]] (UC Berkeley SkyLab) ➔ [[vLLM]]
- [[Tri Dao]] (Princeton) ➔ [[FlashAttention]]
""")

    print(f"[+] Successfully generated Obsidian Vault ({exported_count} notes) at: {vault_dir}")
    print(f"    👉 Obsidian 앱에서 'Open Folder as Vault'로 '{vault_dir}'를 열면 인터랙티브 마크다운 그래프가 바로 열립니다!")

if __name__ == "__main__":
    export_vault()
